name: Android CI Build

on:
  push:
    branches: [ "main" ]
    paths:
      - 'CaseDiaryApp_with_CI.zip'
      - '.github/workflows/unzip-build.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Unzip uploaded project
        run: |
          unzip -o CaseDiaryApp_with_CI.zip -d extracted || true
          if [ -d extracted/CaseDiaryApp ]; then
            shopt -s dotglob || true
            mv extracted/CaseDiaryApp/* .
          else
            shopt -s dotglob || true
            mv extracted/* .
          fi
          ls -la

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew || true

      - name: Build Debug APK
        run: ./gradlew assembleDebug --stacktrace --no-daemon

      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: CaseDiaryApp-debug
          path: app/build/outputs/apk/debug/app-debug.apk
